/*
 * This file is generated by jOOQ.
 */
package com.onlinebookstore.model.tables.records;


import com.onlinebookstore.model.tables.Book;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> implements Record5<Integer, String, Double, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>onlinebookstore.book.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>onlinebookstore.book.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>onlinebookstore.book.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>onlinebookstore.book.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>onlinebookstore.book.price</code>.
     */
    public void setPrice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>onlinebookstore.book.price</code>.
     */
    public Double getPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>onlinebookstore.book.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>onlinebookstore.book.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>onlinebookstore.book.book_detail_id</code>.
     */
    public void setBookDetailId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>onlinebookstore.book.book_detail_id</code>.
     */
    public Integer getBookDetailId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Double, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Double, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Book.BOOK.ID;
    }

    @Override
    public Field<String> field2() {
        return Book.BOOK.NAME;
    }

    @Override
    public Field<Double> field3() {
        return Book.BOOK.PRICE;
    }

    @Override
    public Field<Integer> field4() {
        return Book.BOOK.QUANTITY;
    }

    @Override
    public Field<Integer> field5() {
        return Book.BOOK.BOOK_DETAIL_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Double component3() {
        return getPrice();
    }

    @Override
    public Integer component4() {
        return getQuantity();
    }

    @Override
    public Integer component5() {
        return getBookDetailId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Double value3() {
        return getPrice();
    }

    @Override
    public Integer value4() {
        return getQuantity();
    }

    @Override
    public Integer value5() {
        return getBookDetailId();
    }

    @Override
    public BookRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BookRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public BookRecord value3(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public BookRecord value4(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public BookRecord value5(Integer value) {
        setBookDetailId(value);
        return this;
    }

    @Override
    public BookRecord values(Integer value1, String value2, Double value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Integer id, String name, Double price, Integer quantity, Integer bookDetailId) {
        super(Book.BOOK);

        setId(id);
        setName(name);
        setPrice(price);
        setQuantity(quantity);
        setBookDetailId(bookDetailId);
    }
}
