/*
 * This file is generated by jOOQ.
 */
package com.onlinebookstore.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authorities implements Serializable {

    private static final long serialVersionUID = 1L;

    private String authority;
    private String username;

    public Authorities() {}

    public Authorities(Authorities value) {
        this.authority = value.authority;
        this.username = value.username;
    }

    public Authorities(
        String authority,
        String username
    ) {
        this.authority = authority;
        this.username = username;
    }

    /**
     * Getter for <code>onlinebookstore.authorities.authority</code>.
     */
    public String getAuthority() {
        return this.authority;
    }

    /**
     * Setter for <code>onlinebookstore.authorities.authority</code>.
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    /**
     * Getter for <code>onlinebookstore.authorities.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>onlinebookstore.authorities.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Authorities (");

        sb.append(authority);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
