/*
 * This file is generated by jOOQ.
 */
package com.onlinebookstore.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private String  customerId;
    private Integer bookId;

    public BookUser() {}

    public BookUser(BookUser value) {
        this.customerId = value.customerId;
        this.bookId = value.bookId;
    }

    public BookUser(
        String  customerId,
        Integer bookId
    ) {
        this.customerId = customerId;
        this.bookId = bookId;
    }

    /**
     * Getter for <code>onlinebookstore.book_user.customer_id</code>.
     */
    public String getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>onlinebookstore.book_user.customer_id</code>.
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for <code>onlinebookstore.book_user.book_id</code>.
     */
    public Integer getBookId() {
        return this.bookId;
    }

    /**
     * Setter for <code>onlinebookstore.book_user.book_id</code>.
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookUser (");

        sb.append(customerId);
        sb.append(", ").append(bookId);

        sb.append(")");
        return sb.toString();
    }
}
