/*
 * This file is generated by jOOQ.
 */
package com.onlinebookstore.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String address;
    private String email;
    private String firstName;
    private String lastName;
    private Long   mob;

    public Customer() {}

    public Customer(Customer value) {
        this.id = value.id;
        this.address = value.address;
        this.email = value.email;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.mob = value.mob;
    }

    public Customer(
        String id,
        String address,
        String email,
        String firstName,
        String lastName,
        Long   mob
    ) {
        this.id = id;
        this.address = address;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.mob = mob;
    }

    /**
     * Getter for <code>onlinebookstore.customer.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>onlinebookstore.customer.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>onlinebookstore.customer.address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>onlinebookstore.customer.address</code>.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for <code>onlinebookstore.customer.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>onlinebookstore.customer.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>onlinebookstore.customer.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>onlinebookstore.customer.first_name</code>.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>onlinebookstore.customer.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>onlinebookstore.customer.last_name</code>.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>onlinebookstore.customer.mob</code>.
     */
    public Long getMob() {
        return this.mob;
    }

    /**
     * Setter for <code>onlinebookstore.customer.mob</code>.
     */
    public void setMob(Long mob) {
        this.mob = mob;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customer (");

        sb.append(id);
        sb.append(", ").append(address);
        sb.append(", ").append(email);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(mob);

        sb.append(")");
        return sb.toString();
    }
}
