/*
 * This file is generated by jOOQ.
 */
package com.onlinebookstore.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseDetail implements Serializable {

    private static final long serialVersionUID = 1L;

    private Double  price;
    private Integer quanitity;
    private Integer bookId;
    private String  purchaseHistoryId;

    public PurchaseDetail() {}

    public PurchaseDetail(PurchaseDetail value) {
        this.price = value.price;
        this.quanitity = value.quanitity;
        this.bookId = value.bookId;
        this.purchaseHistoryId = value.purchaseHistoryId;
    }

    public PurchaseDetail(
        Double  price,
        Integer quanitity,
        Integer bookId,
        String  purchaseHistoryId
    ) {
        this.price = price;
        this.quanitity = quanitity;
        this.bookId = bookId;
        this.purchaseHistoryId = purchaseHistoryId;
    }

    /**
     * Getter for <code>onlinebookstore.purchase_detail.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>onlinebookstore.purchase_detail.price</code>.
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * Getter for <code>onlinebookstore.purchase_detail.quanitity</code>.
     */
    public Integer getQuanitity() {
        return this.quanitity;
    }

    /**
     * Setter for <code>onlinebookstore.purchase_detail.quanitity</code>.
     */
    public void setQuanitity(Integer quanitity) {
        this.quanitity = quanitity;
    }

    /**
     * Getter for <code>onlinebookstore.purchase_detail.book_id</code>.
     */
    public Integer getBookId() {
        return this.bookId;
    }

    /**
     * Setter for <code>onlinebookstore.purchase_detail.book_id</code>.
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * Getter for <code>onlinebookstore.purchase_detail.purchase_history_id</code>.
     */
    public String getPurchaseHistoryId() {
        return this.purchaseHistoryId;
    }

    /**
     * Setter for <code>onlinebookstore.purchase_detail.purchase_history_id</code>.
     */
    public void setPurchaseHistoryId(String purchaseHistoryId) {
        this.purchaseHistoryId = purchaseHistoryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PurchaseDetail (");

        sb.append(price);
        sb.append(", ").append(quanitity);
        sb.append(", ").append(bookId);
        sb.append(", ").append(purchaseHistoryId);

        sb.append(")");
        return sb.toString();
    }
}
