/*
 * This file is generated by jOOQ.
 */
package com.onlinebookstore.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        id;
    private LocalDateTime date;
    private String        customerId;

    public PurchaseHistory() {}

    public PurchaseHistory(PurchaseHistory value) {
        this.id = value.id;
        this.date = value.date;
        this.customerId = value.customerId;
    }

    public PurchaseHistory(
        String        id,
        LocalDateTime date,
        String        customerId
    ) {
        this.id = id;
        this.date = date;
        this.customerId = customerId;
    }

    /**
     * Getter for <code>onlinebookstore.purchase_history.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>onlinebookstore.purchase_history.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>onlinebookstore.purchase_history.date</code>.
     */
    public LocalDateTime getDate() {
        return this.date;
    }

    /**
     * Setter for <code>onlinebookstore.purchase_history.date</code>.
     */
    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    /**
     * Getter for <code>onlinebookstore.purchase_history.customer_id</code>.
     */
    public String getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>onlinebookstore.purchase_history.customer_id</code>.
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PurchaseHistory (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(customerId);

        sb.append(")");
        return sb.toString();
    }
}
