/*
 * This file is generated by jOOQ.
 */
package com.onlinebookstore.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShoppingCart implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer count;
    private String  customerId;
    private Integer bookId;

    public ShoppingCart() {}

    public ShoppingCart(ShoppingCart value) {
        this.count = value.count;
        this.customerId = value.customerId;
        this.bookId = value.bookId;
    }

    public ShoppingCart(
        Integer count,
        String  customerId,
        Integer bookId
    ) {
        this.count = count;
        this.customerId = customerId;
        this.bookId = bookId;
    }

    /**
     * Getter for <code>onlinebookstore.shopping_cart.count</code>.
     */
    public Integer getCount() {
        return this.count;
    }

    /**
     * Setter for <code>onlinebookstore.shopping_cart.count</code>.
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * Getter for <code>onlinebookstore.shopping_cart.customer_id</code>.
     */
    public String getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>onlinebookstore.shopping_cart.customer_id</code>.
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for <code>onlinebookstore.shopping_cart.book_id</code>.
     */
    public Integer getBookId() {
        return this.bookId;
    }

    /**
     * Setter for <code>onlinebookstore.shopping_cart.book_id</code>.
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShoppingCart (");

        sb.append(count);
        sb.append(", ").append(customerId);
        sb.append(", ").append(bookId);

        sb.append(")");
        return sb.toString();
    }
}
