/*
 * This file is generated by jOOQ.
 */
package com.onlinebookstore.model;


import com.onlinebookstore.model.tables.Authorities;
import com.onlinebookstore.model.tables.Book;
import com.onlinebookstore.model.tables.BookDetail;
import com.onlinebookstore.model.tables.BookUser;
import com.onlinebookstore.model.tables.Customer;
import com.onlinebookstore.model.tables.PurchaseDetail;
import com.onlinebookstore.model.tables.PurchaseHistory;
import com.onlinebookstore.model.tables.ShoppingCart;
import com.onlinebookstore.model.tables.Users;


/**
 * Convenience access to all tables in onlinebookstore.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>onlinebookstore.authorities</code>.
     */
    public static final Authorities AUTHORITIES = Authorities.AUTHORITIES;

    /**
     * The table <code>onlinebookstore.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>onlinebookstore.book_detail</code>.
     */
    public static final BookDetail BOOK_DETAIL = BookDetail.BOOK_DETAIL;

    /**
     * The table <code>onlinebookstore.book_user</code>.
     */
    public static final BookUser BOOK_USER = BookUser.BOOK_USER;

    /**
     * The table <code>onlinebookstore.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>onlinebookstore.purchase_detail</code>.
     */
    public static final PurchaseDetail PURCHASE_DETAIL = PurchaseDetail.PURCHASE_DETAIL;

    /**
     * The table <code>onlinebookstore.purchase_history</code>.
     */
    public static final PurchaseHistory PURCHASE_HISTORY = PurchaseHistory.PURCHASE_HISTORY;

    /**
     * The table <code>onlinebookstore.shopping_cart</code>.
     */
    public static final ShoppingCart SHOPPING_CART = ShoppingCart.SHOPPING_CART;

    /**
     * The table <code>onlinebookstore.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
